### ISSUE TITLE
Failure to Save Account Show info and FB URL and YouTube URL

### ISSUE THREAD

**Issue by DBASQLGuru** [Remote-Falcon/remote-falcon-issue-tracker#20]
**Your Show Name:**
Changing the show name from Roanoke Christmas Show - to Vlada's Pixel Light Show

**Describe the bug:**
Select the Account area, go to the Show Name , change the show. Add YouTube URL, Add Facebook URL - then a warning displays ( pop-up) about  the change in the RF URL. Click OK.  system logs you out. Log back in, show/account data has not been updated.

Browser - Edge

**Comment by whitesoup12** [comment]
Not able to replicate this. But I did notice when changing the show name I had to refresh the page for it to update.
