### ISSUE TITLE
Time is not being correctly ascertained on Boot-up or Reboot

### ISSUE THREAD

**Issue by DBASQLGuru** [Remote-Falcon/remote-falcon-issue-tracker#27]
Vlada's Pixel Light Show

Inside FPP Settings the Time Tab opens and displays the wrong time. NTP server IP has been provided and works as expected in version 7.5  I have side by side PI machines. Version 8 displays the incorrect time in the top right corner of the screen as well as inside the Time UI Window.

Go to FPP Settings
Click on the Time tab
Set the NTP IP address
System fails to acquire and display the correct time.

![Time Bug](https://github.com/user-attachments/assets/29b080ab-6669-4e87-8e04-942e89cc60b6)

**Comment by DBASQLGuru** [comment]
DNS is enabled and set. Remote Falcon can talk to this device, so we know that it has internet capability.

**Comment by whitesoup12** [comment]
This bug should go to FPP, not Remote Falcon.
