### ISSUE TITLE
Manage Viewer Pages

### ISSUE THREAD

**Issue by waycool5794** [Remote-Falcon/remote-falcon-issue-tracker#29]
South Horseshoe Holiday Lights

Manage Viewer Pages
Cant manage viewer pages will not allow to activate different viewer page.

Cant edit name of viewer page.

![edit](https://github.com/user-attachments/assets/1778e822-8517-463b-bb2f-9562a198cdb7)

![firefox](https://github.com/user-attachments/assets/1c57452f-4f71-4fb4-854f-888fdaa72061)

or am i doing it wrong?

**Comment by whitesoup12** [comment]
You can’t edit page names. And you change your active page from the Viewer Page settings in Remote Falcon Settings menu.
