### ISSUE TITLE
add song countdown timer

### ISSUE THREAD

**Issue by chris051873** [Remote-Falcon/remote-falcon-issue-tracker#35]
would like viewers to be able to see song length and amount of time remaining in current song. I have had many viewers ask about this possibility.

add a count down timer next to currently playing, and a song length to songs in list

**Comment by whitesoup12** [comment]
Time remaining (a countdown) is actually available now. I need to communicate that so people know about it. Totally forgot I added it. lol

**Comment by chris051873** [comment]
that's awesome !  thanks !
