### ISSUE TITLE
voted song is using FPP name

### ISSUE THREAD

**Issue by chris051873** [Remote-Falcon/remote-falcon-issue-tracker#36]
**Your Show Name:**
RavineRunLights(self hosted)

**Describe the bug:**
when a song is voted in it is using the FPP name instead of the renamed song name in RF

**To Reproduce:**
vote on a song and check which name is being used. when the normal FPP playlist is playing the names are using the correct RF re-named songs.

**Expected behavior:**
a voted song should use the RF name

**Screenshots:**
here is a screenshot of playlist showing FPP name and RF name
![image](https://github.com/user-attachments/assets/fc6a4b89-0c3a-4fc8-840c-a0007a85baed)

screenshot of playing in FPP normal playlist
![image](https://github.com/user-attachments/assets/d819fe68-4351-455b-bcc5-0cc6caefb37d)

screenshot of voted in song
![image](https://github.com/user-attachments/assets/6c9872ce-2f58-4e85-a883-1e34c9dffba5)

**Desktop (if issue is seen on desktop, otherwise N/A):**
N/A

**Smartphone (if issue is seen on mobile, otherwise N/A):**
N/A

**Comment by whitesoup12** [comment]
The fix for this has already been made. Make sure you delete the remote-falcon-viewer image completely and re-pull/re-start the service.

**Comment by chris051873** [comment]
could you give me a quick direction of what i need to do to delete and repull. I thought it was just stopping and use the restart.sh

**Comment by chris051873** [comment]
@whitesoup12 
I ran the restart file, it says removed the viewer, 
![image](https://github.com/user-attachments/assets/0764f844-67e6-4daa-ae0a-a32288cff8fa)

i the run the start.sh file and it rebuilds
![image](https://github.com/user-attachments/assets/fb0c84fc-577b-4963-9477-125f846e7396)


problem still exists on voted in songs only, the normal playlist comes across fine with song names

**Comment by whitesoup12** [comment]
This should be fixed now. :)
