### ISSUE TITLE
Jukebox request stats have invalid entries at the beginning of the day before voter control is enabled

### ISSUE THREAD

**Issue by craiz** [Remote-Falcon/remote-falcon-issue-tracker#37]
**Your Show Name:**
IrwinFamilyLights

**Describe the bug:**
RF dashboard shows 19 jukebox requests for Oct 11 2024 but it is 9:00 am in the morning and viewer control has been turned off since my show ended around 10pm on Oct 10.

**To Reproduce:**
Unknown.  Wait for next day and see phantom requests appear in dashboard.

**Expected behavior:**
Requests only show up in stats when a viewer requests a song with viewer control enabled.

**Comment by whitesoup12** [comment]
The timezone issues should be fixed now.
