### ISSUE TITLE
Installation of Remote Falcon Plugin fails 

### ISSUE THREAD

**Issue by GadgetAddict** [Remote-Falcon/remote-falcon-issue-tracker#38]
**Your Show Name:**
OscarLightss

**Describe the bug:**
I cannot install the Remote Falcon plugin in the FPP instance

**To Reproduce:**
1. Go to 'FPP by opening browser and typing fpp.local 
2. Click on content setup Tab, then PLUGIN MANAGER'
3. Scroll down to '.Remote Falcon by author James vance  '
4. Click green install button
5. Error message below; 
 
 Installing plugin remote-falcon
Cloning into 'remote-falcon'...
fatal: unable to access 'https://github.com/remote-falcon/remote-falcon-plugin.git/': Could not resolve host: github.com
Failed to fetch remote-falcon using https://github.com/remote-falcon/remote-falcon-plugin.git -- aborting
{"Status":"Error","Message":"Could not properly install plugin"}

**Expected behavior:**
I EXPECTED the plugin to install so I could reboot the fpp and then access the plugin interface, as indicated in the documentation at https://docs.remotefalcon.com

**Screenshots:**

**Desktop (if issue is seen on desktop, otherwise N/A):**
 - OS: MAC OS 15.0 Sequoia 
 - Browser Safari version 18.0
 - tried also in Browser Chrome 
 
also tried installing a diff plugin and got the same error. 
it says it  cannot resolve host GitHub

FPP NETWORK SETUP.
Physical - cat 6 cable from router to switch 
Raspberry Pi/fpp connected to switch with cat6 cord

FPP IP address is set to static and can be accessed in browser and in XLIGHTS under FPP Connect

<img width="1537" alt="Screenshot 2024-10-12 at 12 45 08 PM" src="https://github.com/user-attachments/assets/841df3ca-9d59-4054-a077-ee149d57c1d1">

**Comment by whitesoup12** [comment]
Your FPP isn’t able to access the internet. You’ll need to verify your network and DNS settings.

**Comment by GadgetAddict** [comment]
DNS was set to DHCP, so I thought it was set correctly.
When I Manually set the DNS Settings on the FPP to 8.8.8.8, then Plugins would install fine. 
closing issue
