### ISSUE TITLE
{PLAYLISTS} not populating any sequences - title only

### ISSUE THREAD

**Issue by RVCTinker** [Remote-Falcon/remote-falcon-issue-tracker#43]
**Your Show Name:**
Tinker Light Show

**Describe the bug:**
I have used RF in the past for Christmas, so my token is valid. I am trying to use it for my Halloween show. I have updated to FPP 8.0 since I last used it. So far I have tried many things to fix this, including removing and re-installing the RF plug-in, but that has not been successful. I am using the "Purple Halloween by StramMade3D" template and I will enclose it in a zip file to this bug report. I have done a test where a straight sequence playlist is used - no lead-in/lead-out, and it is not in the schedule. When I enable viewer control and play the playlist via FPP manually, it never shows the songs of the playlist for people to choose from. I always get it showing the word Halloween even though the playlist is "Halloween - Song List", and at BEST I have gotten it to show the name of the 2nd song while it is playing which is Ghostbusters or sometimes Beetlejuice (intro song which is just a normal sequence at the top of the playlist in this case).

I have customized the sequences - I have put a name, author, image URL and category for all of the Christmas sequences, and I have the name, author, and image URL on a few of the Halloween ones, which I have even removed to see if that causes a problem (not the name, just the other info) and that did not help. 

**To Reproduce:**
1. Set up RF in FPP to sync to Halloween - Song List
2. Sync the playlist
3. Verify the sequences in RF, hide some of the in-between sequences, categorize all of the sequences - also validate that all active sequences correspond with content from the playlist. 
4. Enable viewer control in RF (since I cannot do it in the playlist lead-in), validate the correct viewer page is active, and confirm that the page mode is Jukebox.
5. Go to the Status/Control page in FPP, choose the Halloween - Song List playlist, and start it playing. 
6. Go to the RF Viewer page and see (enclosed) that I cannot select any songs. 

**Expected behavior:**
I should see all of the songs from the playlist listed and be able to click on one to select it.

**Screenshots:**
Enclosed.

**Desktop (if issue is seen on desktop, otherwise N/A):**
 - OS: Windows 11 for browser
 - Browser: Chrome
 - FPP:
FPP Version: | 8.0
Platform: | Raspberry Pi (Pi 4)
FPP OS Build: | v2024-09
OS Version: | Raspbian GNU/Linux 12 (bookworm)
Kernel Version: | 6.6.47-v7l+
System Boot Time: | 2024-10-28 11:43:22
fppd Uptime: | 30:07

**Smartphone (if issue is seen on mobile, otherwise N/A):**
N/A
![RemoteFalcon_Fail](https://github.com/user-attachments/assets/f5cbc174-557d-47e6-9d15-2e393261d34a)
[viewer_page_template.zip](https://github.com/user-attachments/files/17547039/viewer_page_template.zip)

**Comment by RVCTinker** [comment]
I have since upgraded FPP to 8.2 and got the same results.

**Comment by whitesoup12** [comment]
Can you give me a screenshot of the playlist in FPP you're attempting to sync?

**Comment by RVCTinker** [comment]
Here you go.
![Halloween - Song List](https://github.com/user-attachments/assets/48fcc3fe-90a5-4801-9396-6b3fa812b5d6)

**Comment by whitesoup12** [comment]
Try removing all single quotes/apostrophes (like It's, and Somebody's) and re-syncing.

**Comment by whitesoup12** [comment]
Verified that the single quotes don't cause issues. Are you self hosting? I can't find "Tinker Light Show" on RF.

**Comment by RVCTinker** [comment]
No joy. As I have been able to do once in a while, it displays a single song under the word "Halloween" which is Beetlejuice. That is not even a sequence name - that is who I have as the author and is part of the sequence title, but it is missing a lot. As well as Halloween - it should be showing "Halloween - Song List".  So if anything, it appears like the dashes are causing an issue, but I have a LOT of those so not sure if it is feasible to remove all of them easily.

**Comment by RVCTinker** [comment]
No, I am not self-hosting. I gave you the viewer page title, sorry. It is just "Tinker Show".

**Comment by whitesoup12** [comment]
Okay, looks like you have a group called "Halloween" and all your sequences are part of that group. This is why only one sequence named "Halloween" (the name of your group) is showing up. I recommend you review the docs to understand how grouping works. https://docs.remotefalcon.com/docs/docs/control-panel/sequences#sequence-group

**Comment by RVCTinker** [comment]
Oh good grief. You nailed it. I thought those were just for sorting and (ahem) grouping purposes within RF. I - of course - did not read the doc until now on what its true purpose is. (sigh) Oops!   Thanks for finding it!

**Comment by whitesoup12** [comment]
Glad we got it sorted!

**Comment by RVCTinker** [comment]
Can I ask for help in one more area? It has to do with the scheduler and lead-in limitations....

I have my home automation system read the schedule to know when to power up all of the controllers and power supplies, and then when to shut them off at the end of the evening. It does this 5 minutes before the show start, and 5 minutes after the graceful ending. 

With the limitation of not being able to use the schedule, how can I keep Remote Falcon working?  If the playlist is in the schedule and I just use a separate playlist for the lead-in, then what happens with RF by having it in the schedule?  If I do not have it in the schedule, then I would have to send an FPP command to stop gracefully when I want it to end, and that defeats the purpose of me being able to just have the FPP schedule drive everything.

Thanks
