### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by joshwlewis** [Remote-Falcon/remote-falcon-issue-tracker#44]
**Is your feature request related to a problem? Please describe:**

I'm frustrated when I write code to consume an HTTP API and then the API changes; I'm not sure how/what changed.

**Describe the solution you'd like:**

I'd love to see documentation for the HTTP API. 

I had my own currently playing component that used the REST API endpoint `GET remotefalcon.com/remotefalcon/api/external/subdomain/{mydomain}/sequences`. That endpoint 404s now -- I'm not sure if it's moved or if it's totally gone. It seems like Remote Falcon has mostly changed over to GraphQL based on the source code. I'm having to dig through the source to figure out how to get the data again. It'd be nice to have some docs on how to use the API instead of reverse-engineering.

(I know the old API wasn't a publicly documented, and I consumed the API at my own risk.)

Thanks for building and hosting this cool software.

**Comment by whitesoup12** [comment]
Hey, sorry this took so long. Wrapping up the external API work now and should be available soon.

**Comment by whitesoup12** [comment]
@joshwlewis, this is back up and running. Please be sure the check out the new [API docs](https://app.swaggerhub.com/apis/whitesoup12/RemoteFalcon) for the changes that were made.

**Comment by joshwlewis** [comment]
@whitesoup12 thanks so much; that was fast! I did end up consuming the viewer graphQL API, but I may switch back soon. The documentation goes a long way and I'm glad to see it using swagger too.
