### ISSUE TITLE
Make empty {NOW_PLAYING} and {JUKEBOX_QUEUE} placeholders show the word "None" instead of just being blank

### ISSUE THREAD

**Issue by diamondcrescent** [Remote-Falcon/remote-falcon-issue-tracker#47]
When there aren't any songs playing and/or any queued up songs, it looks kind of weird having my "Playing Now" or "Next Requested Songs" titles with no songs listed underneath, so it looks like they're just stacked on top of each other with no purpose. It's a bit confusing to a person who is looking at the web page for the first time and is trying to comprehend how it's used.

Can it be changed so the placeholders such as {NOW_PLAYING} and {JUKEBOX_QUEUE} would display something like the word "None", instead of nothing at all?

**Comment by whitesoup12** [comment]
Playing Now and Playing Next should be populated by what's currently playing inf your normal FPP schedule. If you're not playing anything, then viewer control is likely off and your after hours message is showing.

**Comment by diamondcrescent** [comment]
I was thinking that the {NOW_PLAYING} placeholder would always be showing something as long as the show is running, but the {NEXT_PLAYLIST} and {JUKEBOX_QUEUE} placeholders could be blank in the situation where nobody recently has made a request, though. Is that correct?

________________________________

**Comment by whitesoup12** [comment]
{NEXT_PLAYLIST} should always have a value as well, since it's populated either by the next request or the next scheduled sequence. As for the {JUKEBOX_QUEUE}, I understand what you're saying, but I think having nothing display when the queue is empty is more indicative of an "empty queue" than having it showing something like "No Requests" or "None".

**Comment by djulien** [comment]
I'm also getting a blank {NEXT_PLAYLIST} and {QUEUE_SIZE}.  I was able to work around it by adding the following to my viewer page:
```
<style type="text/css">
#next:empty:before {
    content: 'NONE';
}    
#requested:empty:before {
    content: 'NONE';
}    
</style>

<h2> Up Next </h2>
<div id="next" class="jb-text"> {NEXT_PLAYLIST} </div>
<h2> Requested </h2>
<div id="requested" class="jb-text"> {JUKEBOX_QUEUE} </div>
```

**Comment by diamondcrescent** [comment]
Thank you. That code worked for me. I thought doing trickery like that would have required scripting, which is a big no-no. I'm good enough with HTML to do basic modifications, but not enough to make text/variable manipulations like that.
________________________________
