### ISSUE TITLE
{QUEUE_DEPTH} does not expand if there is other text before it

### ISSUE THREAD

**Issue by djulien** [Remote-Falcon/remote-falcon-issue-tracker#50]
**Your Show Name:**
Adding your show name helps in reproducing the bug.

**Describe the bug:**
The {QUEUE_DEPTH} variable does not get expanded if there is other text before it.  For example:
     <div class="body_text"> {QUEUE_SIZE} </div>
will be expanded correctly, but
     <div class="body_text">queue size is {QUEUE_SIZE} </div>
will not be expanded

**To Reproduce:**
1. add the above HTML into a page template, then go to display-name.remotefalcon.com to see it

**Expected behavior:**
The {QUEUE_DEPTH} variable should be expanded regardless of what surrounds it.  (other variables should likely behave similarly)

**Screenshots:**

**Desktop (if issue is seen on desktop, otherwise N/A):**
n/a - it's a server-side issue

**Smartphone (if issue is seen on mobile, otherwise N/A):**
n/a - it's a server-side issue

**Comment by whitesoup12** [comment]
Try doing `some text <span>{QUEUE_SIZE}</span>`

**Comment by djulien** [comment]
> Try doing `some text <span>{QUEUE_SIZE}</span>`

Thank you for this work-around!
