### ISSUE TITLE
Add nested playlists/sequences during Sync

### ISSUE THREAD

**Issue by djulien** [Remote-Falcon/remote-falcon-issue-tracker#51]
**Is your feature request related to a problem? Please describe:**
In order to reduce duplication, I added some playlists rather than individual sequences into my Remote Falcon playlist.  However, after sync the sequences within nested playlists are not transferred to Remote Falcon, only the sequences that are directly in the Remote Falcon playlist.

**Describe the solution you'd like:**
I would like/expect that any nested sequences within the Remote Falson playlist to also be transferred.  Ideally, the songs would also be auto-categorized by the playlist containing them, but if it at least transferred the flattened list of sequences that would avoid the need to duplicate songs between playlists.

For now I have a little Javascript (node.js) program that I can run on FPP to pull in the nested sequences (attached below), but it would be better if the Remote Falcon plugin did this automatically (or maybe add a checkbox to make it an optional feature). 
[unnest-playlist.rename-this-to-js.txt](https://github.com/user-attachments/files/17840360/unnest-playlist.rename-this-to-js.txt)

**Comment by whitesoup12** [comment]
This isn't likely something I'll add to the plugin simply cause it would require a lot of rework in how the plugin syncs and plays the requested sequences. It's not much more effort to just add the sequences directly.
