### ISSUE TITLE
Wrong song is played if playlist contains nested playlists

### ISSUE THREAD

**Issue by djulien** [Remote-Falcon/remote-falcon-issue-tracker#52]
**Your Show Name:**
LED to Celebrate

**Describe the bug:**
In FPP I have a playlist that contains songs and other (nested) playlists.  I synced it to Remote Falcon.  When I click on a song it shows the correct name in the queue, but then it plays a song further down in the playlist.

**To Reproduce:**
1. In FPP create a playlist, then add some other playlists to it, then add some songs
2. Sync the playlist with Remote Falcon
3. On the Remote Falcon viewer page, click on a song (using jukebox mode)
4. The correct song will show in the queue or up next, but then the wrong song will play

**Expected behavior:**
Play the correct song.

**Screenshots:**
If applicable, add screenshots to help explain your problem. (attached)  The issue might be that the "Sequence Index" in RF is off by the number of entries it skipped (nested playlists).  For example, in the screenshot the sequences start with an index of 5 (there were 4 nested playlists in the RF playlist in FPP), and the song that is played seems to be off by that amount (ie, song #3 will play instead of song #7)

**Desktop (if issue is seen on desktop, otherwise N/A):**
n/a  (server-side issue)
 - OS: Linux
 - Browser; Chromium

**Smartphone (if issue is seen on mobile, otherwise N/A):**
![RF-wrong-song](https://github.com/user-attachments/assets/f5b561fc-738a-4669-adde-660da270e940)

**Comment by whitesoup12** [comment]
The plugin does not support nested playlists in the playlist that is getting synced with RF, so this isn't a bug.

**Comment by djulien** [comment]
well, as long as the documentation says that nested playlists aren't supported. :)
