### ISSUE TITLE
Randomize Playlist Breaks Next Up:

### ISSUE THREAD

**Issue by Rarefy-Dev** [Remote-Falcon/remote-falcon-issue-tracker#53]
**Your Show Name:**
Fannin

**Describe the bug:**
If a playlist has Radomize enabled the Next Up displayed on the external facing site isn't always correct.

**To Reproduce:**
1. Go to playlist for your show playlist.
2. Click on gear to get to settings
3. Change Randomize to "Once Per Load"
4. Hit save, then save playlist
5. Start your main show
6. See error

**Expected behavior:**
I expect Next Up will always have the song that is next to play.

**Screenshots:**
![image](https://github.com/user-attachments/assets/3c29aeda-c4bf-40b2-a7ee-085c66d75da3)
![image](https://github.com/user-attachments/assets/72a740c8-0baa-486c-a2a7-2892c64e9a6c)

**Desktop (if issue is seen on desktop, otherwise N/A):**
 - OS: Mac
 - Browser Chrome

N/A

**Comment by whitesoup12** [comment]
It's not possible in FPP to determine the next schedule sequence when Randomize is enabled.
