### ISSUE TITLE
After Sync from FPP Plug-In, duplicates have the same sequence order

### ISSUE THREAD

**Issue by RVCTinker** [Remote-Falcon/remote-falcon-issue-tracker#54]
**Your Show Name:**
Tinker Show / Tinker Light Show

**Describe the bug:**
My playlist is arranged like this: Song, in-between-sequence, Song 2, in-between-sequence, Song 3, etc.  After doing a sync on FPP via the RF plug-in, all of the in-between-sequence sequences have the same sequence order number - in my case 58. I am also not able to drag-n-drop other sequences to change the order at present (11/26/2024). 

**To Reproduce:**
1. Go to FPP's RF plug-in
2. Set the sequence to Christmas playlist
3. Click Sync with RF
4. Go to the Sequences page in RF (https://remotefalcon.com/control-panel/sequences)
5. See the result - and also try dragging a song to be amongst them or above them and most of the time it does not work.

**Expected behavior:**
Although the name of the sequence is the same, if you are going to list it ~27 times, then each sequence order number should be accurate rather than them all being the same.

**Screenshots:**
![RFSequences](https://github.com/user-attachments/assets/e3598dc0-c150-44ca-b1bd-bab209c2a488)

**Desktop (if issue is seen on desktop, otherwise N/A):**
 - OS: Windows 11
 - Browser: Chrome

**Smartphone (if issue is seen on mobile, otherwise N/A):**
 - Device: N/A
 - Browser N/A

**Comment by whitesoup12** [comment]
Why are you putting duplicates in your RF playlist?

**Comment by RVCTinker** [comment]
My show does not stream songs constantly. Especially when I have only a 
few (e.g. 3) songs at Thanksgiving, I have "In Between" sequences that 
are general (typically non-audio) sequences to entertain people until 
the next song. For Christmas, these sequences are short (e.g. 10 
seconds) and they display a count-down to the next song. So my playlists 
for Halloween, Thanksgiving, and Christmas run from sunset until 9:30PM 
Sun-Thurs and 11PM Friday and Saturday which, if they played the music 
sequences constantly would drive the neighbors nuts. I have speakers and 
a transmitter on my setup because I get a lot of people walking by the 
show that do not have radios with them.

Nonetheless, that is my setup!


------ Original Message ------
Subject Re: [Remote-Falcon/remote-falcon-issue-tracker] After Sync from 
FPP Plug-In, duplicates have the same sequence order (Issue #54)

**Comment by whitesoup12** [comment]
Okay, it sounds like the same playlist you use for your schedule you're also syncing with RF, which you shouldn't do. You should have a playlist that is used **only** for getting sequences into RF for viewers to choose from.

**Comment by RVCTinker** [comment]
Yeah... but I do not understand in my environment how to make that work. 
I *need* a scheduled item that I can key off of to have my automation 
system turn on all of the power supplies/controllers/radio/transmitter 
for my show.

Typically I would have the lead-in, show, and lead-out. Lead-in is an 
introduction and enabling the Remote Falcon. This year, I created a 
blank sequence of the right amount of time so that I could move my 
lead-in content into a separately scheduled item that runs for a 
specific amount of time (5 minutes), and that way I could schedule the 
main show and know exactly when it should start (5 minutes later than 
the lead-in playlist).

Then my main show has the songs and the in-between sequences, and that 
repeats. That is another thing I need is the schedule because it will 
run through all of the songs with all of the time available from sunset 
until the show ends.

Then, after the ending time, I have another playlist that turns off the 
Remote Falcon features.

That middle playlist that repeats and has the songs and the in-between 
sequences. I have a song-list only that has the songs but not the 
in-between ones. If I use that for Remote Falcon, I still have the fact 
that my regular playlist is scheduled and repeats until it ends 
gracefully at the scheduled time.

Can you tell me if I use that separate song-only playlist with Remote 
Falcon that the rest of this setup will work?  e.g. When somebody 
requests song(s) it will play them, and then switch back to the original 
playlist and resume where it was?

Just so you know specifics:


The Christmas - Lead In and Christmas - Lead Out playlists do not 
actually use the Lead In or Lead Out features, they are just so that I 
do not have to use a Lead In or Lead Out in my main playlist because RF 
does not like that either.

Thanks


------ Original Message ------
From "whitesoup12" ***@***.***>
To "Remote-Falcon/remote-falcon-issue-tracker" 
***@***.***>
Cc "Tink" ***@***.***>; "Author" ***@***.***>
Date 11/26/2024 1:37:33 PM
Subject Re: [Remote-Falcon/remote-falcon-issue-tracker] After Sync from 
FPP Plug-In, duplicates have the same sequence order (Issue #54)

**Comment by whitesoup12** [comment]
I recommend NOT using lead ins or lead outs for RF commands. Instead, you should schedule them. I added a screenshot with an example of what I do. Every night before the show starts, I purge the queue and turn on viewer control. After that, I have a Show playlist that runs. Then at the end of the night I turns off viewer control and purge the queue again (to prevent requests from making my show run late). When a request comes in, it will play the request and, assuming there are no other requests, it will go back to your normal scheduled show.

![image](https://github.com/user-attachments/assets/d14b66ce-e1cb-4b58-9e64-9d5cb13d6edb)

**Comment by RVCTinker** [comment]
Yeah, that is pretty much why I wrote: "The Christmas - Lead In and 
Christmas - Lead Out playlists do not actually use the Lead In or Lead 
Out features, they are just so that I do not have to use a Lead In or 
Lead Out in my main playlist because RF does not like that either. "

The "Lead In" playlist is a 1-time playlist that has those commands, a 
filler/empty sequence and a song so that the total runtime of that is 5 
minutes, and that allows me to be pretty precise about the start of the 
"Christmas" playlist which repeats after it.

The "Lead Out" is the same as what you have.

So is the scheduled/repeating Christmas list a problem with RF or do you 
think it will be fine?


------ Original Message ------
From "whitesoup12" ***@***.***>
To "Remote-Falcon/remote-falcon-issue-tracker" 
***@***.***>
Cc "Tink" ***@***.***>; "Author" ***@***.***>
Date 11/26/2024 2:24:31 PM
Subject Re: [Remote-Falcon/remote-falcon-issue-tracker] After Sync from 
FPP Plug-In, duplicates have the same sequence order (Issue #54)

**Comment by RVCTinker** [comment]
How is this completed? The original bug report was for the duplicate sequence number for all of the in-between sequences. That has not been addressed or resolved.

**Comment by whitesoup12** [comment]
It's a non-issue because there is no reason for there to be duplicate sequences in the playlist that gets synced with RF.

**Comment by RVCTinker** [comment]
I provided the reason they exist, and it is because that is the way I 
have my show set up. How can you say there is no reason?

I have 30 seconds between each song in a list of 30 songs, and in those 
30 seconds I display tune-to information and the URL for RemoteFalcon. 
So while I do "hide" the visibility of those in-between songs, it is 
still a bug that each one of those shows a sequence order of 58 and that 
the show cannot be displayed in sequence order correctly.




------ Original Message ------
From "whitesoup12" ***@***.***>
To "Remote-Falcon/remote-falcon-issue-tracker" 
***@***.***>
Cc "Tink" ***@***.***>; "Author" ***@***.***>
Date 11/30/2024 10:38:58 AM
Subject Re: [Remote-Falcon/remote-falcon-issue-tracker] After Sync from 
FPP Plug-In, duplicates have the same sequence order (Issue #54)

**Comment by whitesoup12** [comment]
But you don't need those 30 second in-between sequences in the playlist you sync with RF. Those in-between sequences would only belong in the scheduled playlist.

**Comment by RVCTinker** [comment]
OK - so you are confirming that the sync list does not need to have all 
of the same songs as the scheduled list. Got it.

Thanks



------ Original Message ------
From "whitesoup12" ***@***.***>
To "Remote-Falcon/remote-falcon-issue-tracker" 
***@***.***>
Cc "Tink" ***@***.***>; "Author" ***@***.***>
Date 11/30/2024 11:35:59 AM
Subject Re: [Remote-Falcon/remote-falcon-issue-tracker] After Sync from 
FPP Plug-In, duplicates have the same sequence order (Issue #54)

**Comment by whitesoup12** [comment]
Correct, that’s one of the benefits of RF. You can give your viewers access to request sequences that are not part of your normal schedule.
