### ISSUE TITLE
Songs with the same display name get mixed up in now playing.

### ISSUE THREAD

**Issue by jeffu231** [Remote-Falcon/remote-falcon-issue-tracker#57]
**Your Show Name:**
Self hosted running latest as of 11/26/2024

**Describe the bug:**
I have two versions of the Carol of the Bells in my show. The actual sequence names are different, but the display names are the same. They each have a different artist specified in the RF display meta data. When the show plays the now playing artist title is sometimes the other version not playing. It is almost like is is using the display name as the lookup in a list instead of the sequence name.

**To Reproduce:**
Add two sequences with different names, sync the playlist and then set the display name for both of them to be the same with different artists. Observe when they are playing that the Now Playing will randomly show the wrong artist. 

**Expected behavior:**
Songs of the same display name show the correct artist.

**Comment by whitesoup12** [comment]
This has been fixed. You'll need to delete the images and re-pull.
