### ISSUE TITLE
Remote Falcon Commands not working from FPP

### ISSUE THREAD

**Issue by TechYourFacts** [Remote-Falcon/remote-falcon-issue-tracker#58]
**Your Show Name:**
Pixel Arches

**Describe the bug:**
I'm not sure when this started but the Remote Falcon commands that are in FPP are no longer working. I first noticed it this morning when I noticed that the queue was still visible on the site from last nights show. I then went into FPP and tried to run the commands Remote Falcon - Turn Viewer Control On, Remote Falcon - Turn Viewer Control Off and Remote Falcon - Purge Queue/Reset Votes and none of them are working now..

**To Reproduce:**
I go into Command Presets on FPP and try to run the Remote Falcon commands from there.

**Comment by TechYourFacts** [comment]
I also just noticed that the requests that are made on the site are being queued but FPP is not switching over to them after the current sequence is played. I went into the Remote Falcon plug in on FPP and made sure that the Show token was still correct and also that the plug in said "No issues found with the plugin." This seems to have started within the last couple days as requests were working as of then.

**Comment by whitesoup12** [comment]
I just verified the commands are working, as well as requests and votes. What version FPP and plugin are you on?

**Comment by TechYourFacts** [comment]
I'm currently running FPP Version: 8.3.1 and Remote Falcon Plugin v2024.10.30.2. Thank you!

**Comment by whitesoup12** [comment]
Okay, that's what I tested with as well. Not seeing any issues with it. Does your FPP device have a good internet connection?

**Comment by TechYourFacts** [comment]
It is hard wired and I'm able to reach the FPP GitHub with no issues. To test I just uninstalled the remote falcon plugin and was able to reinstall. The issue is still occurring after that. I am able to update the Remote Playlist from the plugin and that does update the playlist on my Remote Falcon account but everything else seems to not work. I really appreciate your help.

**Comment by TechYourFacts** [comment]
The Remote Falcon site says it is on version 2024.11.28. I'm not sure what the update was yesterday.

**Comment by TechYourFacts** [comment]
I'm so sorry I feel like an idiot but I have this resolved. It was something on my side. Again thank you for all your help.
