### ISSUE TITLE
Turn Managed PSA ON or OFF Commands not functioning

### ISSUE THREAD

**Issue by ljbrusta** [Remote-Falcon/remote-falcon-issue-tracker#61]
**Your Show Name:**
LightsOfSilverhills

**Describe the bug:**
From the scheduler command for Turn Managed PSA ON or OFF are not functioning. There is no error but the normal Green banner that shows it ran never pops up. Turn viewer control on is functioning. 

When you run it manually (haven't tested allowing shedule to run it) **_FPPD can be stopped but it will not start again without a full reboot of the Pi Player_** 

**To Reproduce:**
1. Go to scheduler
2. Add new command and select either of the Managed PSA commands
3. select run now
4. no error and the setting never changes in RF
5. ** FPPD can be stopped but it will not start again without a full reboot of the Pi Player **

**Expected behavior:**
Should turn on or off the Manage PSA setting in RF

**Screenshots:**
![image](https://github.com/user-attachments/assets/9bf04525-c5de-48d1-8f00-5a45a2f351f6)

**Desktop (if issue is seen on desktop, otherwise N/A):**
NA

**Smartphone (if issue is seen on mobile, otherwise N/A):**
NA

**FPP version:**
7.2 with Remote Falcon Plugin v2024.11.29.1

**Comment by ljbrusta** [comment]
Validated that if it runs from the schedule automated it also hangs the system and FPPD will not restart. It will stop but will not restart until the FPP is rebooted.

**Comment by ljbrusta** [comment]
Updated my player to 8.3 now when I run now on the psa command it takes a few seconds and returns the banner completed but it now generates a crash report. So the new FPPD is handling the issue better but the command still fails brutally.

**Comment by joeharrison714** [comment]
Just had this issue. In the fpp log it says:
`2024-12-02 17:40:42.570 (8643) [Plugin] /opt/fpp/src/Plugins.cpp:281: We failed to exec our command callback:  Permission denied`
`2024-12-02 17:40:42.571 (8643) [Plugin] /opt/fpp/src/Plugins.cpp:283:   /home/fpp/media/plugins/remote-falcon/commands//managed_psa_on.php`

**Comment by whitesoup12** [comment]
Fixed file permissions in https://github.com/Remote-Falcon/remote-falcon-plugin/pull/85, Plugin version 2024.12.02.1.
