### ISSUE TITLE
WERFault (Windows Error Reporting module) causes crash when XLights is rendering the attached Sequence

### ISSUE THREAD

**Issue by DBASQLGuru** [Remote-Falcon/remote-falcon-issue-tracker#75]
Vlad's Pixel Light Show

**Describe the bug:**
Begin a new sequence, 
add the media
Import the  sequence form the vendor
Map the sequence using a mapping file
save the file as the name of the sequence for my show
Hit the render all button - let run for about 10 minutes (plus/minus a few minutes )
A Windows machine will throw an error that kills the screen, no output, except a small flag that references "WERFault"

Force system shutdown to restore system functionality

I can't find the error logs from XLights   may not even have time to write a crash dump 

**Expected behavior:**
A full render of this sequence was expected to be completed, both using Batch Render and individual render

 - OS: [e.g. Windows]
 - Browser [ Edge]

[What-Child-is-This.zip](https://github.com/user-attachments/files/18104422/What-Child-is-This.zip)
[XLights 2024 17 64 bit Ellie Zamudio What Child Is This.zip](https://github.com/user-attachments/files/18104436/XLights.2024.17.64.bit.Ellie.Zamudio.What.Child.Is.This.zip)

**Comment by whitesoup12** [comment]
This is the wrong repository. You'll want to put this issue on the xLights repo. https://github.com/xLightsSequencer/xLights
