### ISSUE TITLE
Manual GPS Location

### ISSUE THREAD

**Issue by Beckanator** [Remote-Falcon/remote-falcon-issue-tracker#82]
The GPS picks a location 5 miles from where I am. I tried refreshing many times and then checked my reported location. This is a local issue with computer settings, as with Google's GPS method. However, it could be overcome if manual location entry was possible. 

Thanks!

**Comment by Beckanator** [comment]
I came up with a workaround. When using the Remote-Falcon app on my mobile device, I update the map location to my actual location—constantly learning something. Thanks!

**Comment by whitesoup12** [comment]
Just an added FYI, you can manually enter the lat/long in the input fields.

**Comment by Beckanator** [comment]
Okay, thank you for that. I'm catching on. Many thanks and Happy New Year!

Jeff Bekeris
